### PR TITLE
Dockerize the ember-lightning server

### PR DESCRIPTION
**Pull request by inkblot**
Add a Dockerfile that preps and runs index.js, and supplies it with the
relevant environment variables. Modify index.js to respond to REDIS_SECRET only
when it is set.

### CODE REVIEW

**Comment by philipheinser** [comment]
@inkblot  Thanks this is great!

**Comment by philipheinser** [comment]
@inkblot Should we say that we support docker in our README.md?

**Comment by inkblot** [comment]
Sure? I haven't actually pushed a built docker image except to a private repo that I've been using while I try to set up an ember-cli-deploy infrastructure.

**Comment by inkblot** [comment]
So for reference, here's how I spun it up:

```
docker run -d --name redis-server redis:2.8
docker run -d -P 80:3000 --link redis-server:redis --name ember-lightning-server ember-lightning
```

And also, I'm still busy terraforming the rest of the pieces like S3 and (for production deployment) an Elasticache Redis instance, so I haven't done a full system test yet.

**Comment by inkblot** [comment]
I think I just realized something important about this code, too, but I'm not sure. Is it intended to run on a per-ember app basis? I missed the APP_NAME variable.

**Comment by philipheinser** [comment]
Yes this code is supposed to serve one ember app instance.

**Comment by philipheinser** [comment]
OK

**Comment by inkblot** [comment]
So I have some operational experience with the resulting Docker image now. I'll write up some documentation for it on another branch when I get a chance. The short version is: it works.

**Comment by philipheinser** [comment]
@inkblot :+1:

**Pull request merged**
